# Generated by Django 2.0.4 on 2018-05-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
    ]
