# Generated by Django 2.0.4 on 2018-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180521_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='attending_event',
            new_name='attending',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='not_attending_event',
            new_name='not_attending',
        ),
        migrations.AlterField(
            model_name='attending',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
