# Generated by Django 2.0.4 on 2018-05-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattendance',
            old_name='person_key',
            new_name='username',
        ),
    ]
